#!/bin/bash
branchname=$1
# check out main branch
git checkout main
# pull main branch from repo
git pull
# check out new post branch with pass variable as branch name
git checkout -b "post/$branchname"
# create new file with branch name in /posts directory
touch ./posts/$branchname
