#!/bin/bash
branchname=$1
# check out main branch
git checkout main
# pull main branch from repo
git pull
# check out new update branch with pass variable as branch name
git checkout -b "update/$branchname"
